<template>
  <div>
    <div
      class="pl-3 pb-2 fields-header v-div-button v-hover p-ripple"
      style="cursor: pointer"
      v-text="header"
      @click="isVisible = !isVisible"
    />

    <template v-if="isVisible">
      <VDivButton
        v-for="item in workbooks"
        :key="item.name"
        :label="item.name"
        @click="goto(item)"
        :hover-to-show-slot-after="true"
        class="slide-right"
      >
        <template #before>
          <i :class="getIconClass(item)" />
        </template>
      </VDivButton>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, PropType, ref } from 'vue';
import router from '@/ts/router';
import { WorkbookDefinition } from '@/ts/middleware/web-api';

const props = defineProps({
  workbooks: {
    type: Object as PropType<WorkbookDefinition[]>,
    required: true,
  },
  title: {
    type: String,
    default: 'Workbooks',
  },
  visible: {
    type: Boolean,
    default: true,
  },
});

const goto = (item: WorkbookDefinition): void => {
  router.push(`/${item.shortId}`);
};

const isVisible = ref(props.visible);
const header = computed(() => props.title + (isVisible.value ? '' : ' ...'));
const getIconClass = (row: WorkbookDefinition) => `pl-2 pr-2 pi ${row.icon}`;
</script>

<style lang="scss" scoped>
.slide-right {
  -webkit-animation: slide-right 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-right 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-11-17 11:20:33
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-right {
  0% {
    -webkit-transform: translateX(30px);
            transform: translateX(30px);
  }
  100% {
    -webkit-transform: translateX(0px);
            transform: translateX(0px);
  }
}
@keyframes slide-right {
  0% {
    -webkit-transform: translateX(30px);
            transform: translateX(30px);
  }
  100% {
    -webkit-transform: translateX(0px);
            transform: translateX(0px);
  }
}

</style>
